"""Update service request status and remove cascade deletes

Revision ID: 82cbc7ec5eec
Revises: 74c7b17bcbcc
Create Date: 2024-11-28 23:17:26.530244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cbc7ec5eec'
down_revision = '74c7b17bcbcc'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    op.execute("UPDATE professional SET status = 'pending'")
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)  # Remove default after setting values



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
