"""Added pincode column to Customer

Revision ID: e0cdefe7a135
Revises: 362a48fbdb65
Create Date: 2024-11-26 00:26:15.755572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cdefe7a135'
down_revision = '362a48fbdb65'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=100), nullable=False, server_default='000000'))
        batch_op.alter_column('pincode', server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    # ### end Alembic commands ###
