"""Added more columns in customer and professional 

Revision ID: fbd0366d7877
Revises: 045d73b0e63d
Create Date: 2024-11-26 02:03:34.325658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd0366d7877'
down_revision = '045d73b0e63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=120), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('pincode',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('service_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('document', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('pincode', sa.String(length=6), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('pincode')
        batch_op.drop_column('document')
        batch_op.drop_column('experience')
        batch_op.drop_column('service_name')
        batch_op.drop_column('fullname')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('pincode',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
